### ISSUE TITLE
这个是重复签到的原因吗？

### ISSUE THREAD

**Issue by iSteveyang** [GamerNoTitle/wyycg-autocheckin#11]
> 第1个账号签到失败，回显状态码为400，具体错误信息如下：
> pk2PjJ+MTWWmqFdNkJ2djpqPkE1lXGFbXFdNkJ2dmJ6STWVNoJ6QnUuelJKZS5+aj4ykTVdNkJ2dmJ6SjplNZU2HoGCRYF6HoGBkXWSHoGCPkV2HoGKNYpCHoGBdXltNqDU=

之前类似的issue #5 也看了，最后没看懂我这是不是新问题，base64也看不出是什么

我访问网址取得`cookie`的时候还没签到，第一次`run`，tele的bot忘记`/start`了，搞定后`re-run jobs`就出这个错了

看了wy官网是签到了，但报错不清楚哪里的问题，希望能解决，谢谢大佬

**Comment by GamerNoTitle** [comment]
对，重复签到会返回400的Bad Request
telebot发送信息前当天的签到操作就已经完成了，所以rerun的时候就会因为重复签到而返回失败结果

On Tue, 22 Dec 2020 02:04:41 +0800,  wrote:
> > 第1个账号签到失败，回显状态码为400，具体错误信息如下：
> > pk2PjJ+MTWWmqFdNkJ2djpqPkE1lXGFbXFdNkJ2dmJ6STWVNoJ6QnUuelJKZS5+aj4ykTVdNkJ2dmJ6SjplNZU2HoGCRYF6HoGBkXWSHoGCPkV2HoGKNYpCHoGBdXltNqDU=
> 
> 之前类似的issue #5 也看了，最后没看懂我这是不是新问题，base64也看不出是什么
> 
> 我访问网址取得`cookie`的时候还没签到，第一次`run`，tele的bot忘记`/start`了，搞定后`re-run jobs`就出这个错了
> 
> 看了wy官网是签到了，但报错不清楚哪里的问题，希望能解决，谢谢大佬
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/11
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail
