### ISSUE TITLE
 Repository secrets 中设定 GITHUB_TOKEN 问题。

### ISSUE THREAD

**Issue by wangmanv2** [GamerNoTitle/wyycg-autocheckin#15]
奇怪为什么我在Repository secrets 中设定名称为 GITHUB_TOKEN 就会提示名称无效？你们都设定成功么？

**Comment by GamerNoTitle** [comment]
啊这个。。。仓库里面secrets不用加GITHUB_TOKEN项，只需要在自己的账户里生成一个就行了，GITHUB_TOKEN这个名字就是Github指定用来读取用户密钥的

**Comment by GamerNoTitle** [comment]
这就是为啥我写着密钥名字一定要是GITHUB_TOKEN

**Comment by wangmanv2** [comment]
啊这个。。。那意味着我生成完成后不用修改任何对象嘛？这个生成的不是随机token么？我不是很了解。

**Comment by GamerNoTitle** [comment]
生成完了就可以不用管了，Github自身会去读取这个密钥的

On Mon, 4 Jan 2021 08:09:04 +0800,  wrote:
> 啊这个。。。那意味着我生成完成后不用修改任何对象嘛？这个生成的不是随机token么？我不是很了解。
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/15#issuecomment-753697012
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by wangmanv2** [comment]
OK
