### ISSUE TITLE
Workflows无法运行AutoSignin，只能运行KeepActionAlive

### ISSUE THREAD

**Issue by wdy3334** [GamerNoTitle/wyycg-autocheckin#16]
AutoSignin没有Run workflow 的选项，而且运行完KeepActionAlive也没有什么反馈

**Comment by GamerNoTitle** [comment]
Autosighin的确没有run workflow的选项啊。。。它的运行方式是戳个STAR。。。（主要是这是我之前写的yml就懒得加了，所以跟KeepAlive的运行方式不一样）
KeepAlive运行完后会在你的仓库push一个UUID.txt来达到仓库有更改的效果，从而防止Github禁用你的workflow

On Wed, 6 Jan 2021 17:51:27 +0800,  wrote:
> AutoSignin没有Run workflow 的选项，而且运行完KeepActionAlive也没有什么反馈
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/16
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by GamerNoTitle** [comment]
刚加了个按钮，你自己更新一下自己仓库的脚本吧，不知道怎么更新的话去看看README吧。 :)

-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by wdy3334** [comment]
> 刚加了个按钮，你自己更新一下自己仓库的脚本吧，不知道怎么更新的话去看看README吧。 :)
> 
> 
> -- 
> 
> GamerNoTitle (\^3^/)
> Sent by using BlackBerry 9720 LogicMail

好的，谢谢大佬指点
