### ISSUE TITLE
回显状态码401

### ISSUE THREAD

**Issue by yukiryo** [GamerNoTitle/wyycg-autocheckin#17]
感谢使用来自GamerNoTitle的网易云游戏自动签到脚本！
    今日签到结果如下：
    成功数量：0/3
    失败数量：6/3
    具体情况如下：
    第1个账号验证失败！请检查Cookie是否过期！或者附上报错信息到 https://github.com/GamerNoTitle/wyycg-autosignin/issues 发起issue<br> 第1个账号签到失败，回显状态码为401，具体错误信息如下：{"data":{}<br>"errcode":1006<br>"errmsg":"invalid token"<br>"errmsgcn":"\\u767b\\u5f55\\u4fe1\\u606f\\u5931\\u6548\\uff0c\\u8bf7\\u91cd\\u65b0\\u767b\\u5f55"}\n<br>

**Comment by GamerNoTitle** [comment]
![image](https://user-images.githubusercontent.com/28426291/103963165-93fff680-5193-11eb-9aab-784b3069276e.png)
要不你重新登陆试试？
你这个账号数量也不对，是有三个账号吗？如果是的话估计我的技术逻辑有问题……

**Comment by yukiryo** [comment]
确实是三个，那我弄两个试试

**Comment by GamerNoTitle** [comment]
我估计不是数量问题，我觉得可能是你的Cookie填得有问题，如果方便的话，把你在cookie字段的内容私发到admin@bili33.top，我顺带看一下

On Fri, 8 Jan 2021 12:07:55 +0800,  wrote:
> 确实是三个，那我弄两个试试
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/17#issuecomment-756533658
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by yukiryo** [comment]
我试了两个是可以的

**Comment by GamerNoTitle** [comment]
> 我试了两个是可以的

那你再试试三个？可能三个的情况下我的变量读取不太对？

**Comment by GamerNoTitle** [comment]
你还在吗？你可以试试三个账号嘛？这样我方便找出错误
另外看你Action的日志，第一个账号验证是失败的，你把第一个账号重新登录一下试试

**Comment by yukiryo** [comment]
感谢使用来自GamerNoTitle的网易云游戏自动签到脚本！
    今日签到结果如下：
    成功数量：1/4
    失败数量：3/4
    具体情况如下：
    第1个账号签到失败，回显状态码为400，具体错误信息如下：sFeZlqmWV2+wsmFXmqenmKSZmldvZmtlZmFXmqenoqicV29Xqqiap1WonpyjVamkmZauV2FXmqenoqicmKNXb1eRqmqbamiRqmpuZ26RqmqZm2eRqmyXbJqRqmpnaGVXsj8=<br> 第2个账号签到失败，回显状态码为400，具体错误信息如下：zHO1ssWyc4vMzn1ztsPDtMC1tnOLgoeBgn1ztsPDvsS4c4tzxsS2w3HEuri/ccXAtbLKc31ztsPDvsS4tL9zi3Otxoa3hoStxoaKg4qtxoa1t4OtxoiziLatxoaDhIFzzls=<br> 第3个账号签到成功！<br> 第4个账号签到失败，回显状态码为400，具体错误信息如下：cxpcWWxZGjJzdSQaXWpqW2dcXRoyKS4oKSQaXWpqZWtfGjIabWtdahhrYV9mGGxnXFlxGiQaXWpqZWtfW2YaMhpUbS1eLStUbS0xKjFUbS1cXipUbS9aL11UbS0qKygadQI=
    GamerNoTitle: https://bili33.top
    网易云游戏自动签到脚本: https://github.com/GamerNoTitle/wyycg-autocheckin
可以了，可能是我cookie的问题

**Comment by GamerNoTitle** [comment]
好的 那我关闭issue了 :D
