### ISSUE TITLE
图床炸了

### ISSUE THREAD

**Issue by axcdxz** [GamerNoTitle/wyycg-autocheckin#2]
如题

**Comment by GamerNoTitle** [comment]
https://blog.csdn.net/qq_34018668/article/details/110732639
暂时先看这里吧 虽然不是最新的但是大差不差
可以用的变量名为
![image](https://user-images.githubusercontent.com/28426291/218246746-60ad0427-f723-4e13-b544-4bdda7308cab.png)
多用户cookie用`#`分开

**Comment by GamerNoTitle** [comment]
修好了 可以直接看文档
