### ISSUE TITLE
actions执行中报错

### ISSUE THREAD

**Issue by feilongproject** [GamerNoTitle/wyycg-autocheckin#24]
我在测试多账号时运行actions报错，
账号其中有一个已经签到，两个未签到
请问这是什么原因引起的？

------
cookie内容：
```
Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#
Bearer yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
#
Bearer zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```
报错内容：
```
up]Run python3 main.py "***
[网易云游戏自动签到]脚本运行错误，具体请参见日志！
检测到3个账号，即将开始签到！
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    if me.status_code != 200 and not autherror:
AttributeError: 'NoneType' object has no attribute 'status_code'
Error: or]Process completed with exit code 1.
```

**Comment by GamerNoTitle** [comment]
看起来好象是me这个变量的值是None?
明天下午回家我再看
现在人在学校

On Fri, 19 Feb 2021 21:36:21 +0800,  wrote:
> 我在测试多账号时运行actions报错，
> 账号其中有一个已经签到，两个未签到
> 请问这是什么原因引起的？
> 
> ------
> cookie内容：
> ```
> Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> #
> Bearer yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
> #
> Bearer zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
> ```
> 报错内容：
> ```
> up]Run python3 main.py "***
> [网易云游戏自动签到]脚本运行错误，具体请参见日志！
> 检测到3个账号，即将开始签到！
> Traceback (most recent call last):
>   File "main.py", line 121, in <module>
>     if me.status_code != 200 and not autherror:
> AttributeError: 'NoneType' object has no attribute 'status_code'
> Error: or]Process completed with exit code 1.
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/24
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by GamerNoTitle** [comment]
诶等下 你的cookie分割是
```
Bearer xxx#Bearer yyy#Bearer zzz
```
还是
```
Bearer xxx
#
Bearer yyy
#
Bearer zzz
```

**Comment by feilongproject** [comment]
分行的

**Comment by feilongproject** [comment]
> 诶等下 你的cookie分割是
> 
> ```
> Bearer xxx#Bearer yyy#Bearer zzz
> ```
> 
> 还是
> 
> ```
> Bearer xxx
> #
> Bearer yyy
> #
> Bearer zzz
> ```

分行的

**Comment by GamerNoTitle** [comment]
你要不试试不分行？分行可能会导致分割字符串的时候出问题

On Sat, 20 Feb 2021 15:28:13 +0800,  wrote:
> > 诶等下 你的cookie分割是

> > 

> > ```

> > Bearer xxx#Bearer yyy#Bearer zzz

> > ```

> > 

> > 还是

> > 

> > ```

> > Bearer xxx

> > #

> > Bearer yyy

> > #

> > Bearer zzz

> > ```

> 

> 分行的

> 

> -- 

> You are receiving this because you commented.

> Reply to this email directly or view it on GitHub:

> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/24#issuecomment-782578546
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail
