### ISSUE TITLE
Cookies 出错？

### ISSUE THREAD

**Issue by RimuruW** [GamerNoTitle/wyycg-autocheckin#26]
遇见一个奇怪的问题...

Cookies 是从 [官网](https://cg.163.com/#/pc) 复制的，检查了应该也没出错。直接复制粘贴应该也没有打错的可能。脚本出现了有关 Cookies 的报错。

Cookies 格式是以 bearer + 空格 + 字符串 组成，复制时这些部分也没有少。

报错如下：
```python
Traceback (most recent call last):
  File "main.py", line 191, in <module>
    raise ScriptRunError
__main__.ScriptRunError
[网易云游戏自动签到]脚本运行错误，具体请参见日志！
检测到1个账号，即将开始签到！

    感谢使用来自GamerNoTitle的网易云游戏自动签到脚本！
    今日签到结果如下：
    成功数量：0/1
    失败数量：1/1
    具体情况如下：
    第1个账号验证失败！请检查Cookie是否过期！或者附上报错信息到 https://github.com/GamerNoTitle/wyycg-autosignin/issues 发起issue
    GamerNoTitle: https://bili33.top
    网易云游戏自动签到脚本: https://github.com/GamerNoTitle/wyycg-autocheckin
```

**Comment by GamerNoTitle** [comment]
官网的cookie前面的b不是大写嘛。。。
建议在检查一次如果没问题的话建议重新登录获取

On Sun, 14 Mar 2021 15:41:37 +0800,  wrote:
> 遇见一个奇怪的问题...
> 
> Cookies 是从 [官网](https://cg.163.com/#/pc) 复制的，检查了应该也没出错。直接复制粘贴应该也没有打错的可能。脚本出现了有关 Cookies 的报错。
> 
> Cookies 格式是以 bearer + 空格 + 字符串 组成，复制时这些部分也没有少。
> 
> 报错如下：
> ```python
> Traceback (most recent call last):
>   File "main.py", line 191, in <module>
>     raise ScriptRunError
> __main__.ScriptRunError
> [网易云游戏自动签到]脚本运行错误，具体请参见日志！
> 检测到1个账号，即将开始签到！
> 
>     感谢使用来自GamerNoTitle的网易云游戏自动签到脚本！
>     今日签到结果如下：
>     成功数量：0/1
>     失败数量：1/1
>     具体情况如下：
>     第1个账号验证失败！请检查Cookie是否过期！或者附上报错信息到 https://github.com/GamerNoTitle/wyycg-autosignin/issues 发起issue
>     GamerNoTitle: https://bili33.top
>     网易云游戏自动签到脚本: https://github.com/GamerNoTitle/wyycg-autocheckin
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/26
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by GamerNoTitle** [comment]
![image](https://user-images.githubusercontent.com/28426291/111065419-86008600-84f4-11eb-9503-e0586b17fc15.png)

请问你的变量设置对了嘛……第一个“”里面是cookie，你这里传入值为空

**Comment by RimuruW** [comment]
抱歉，劳烦费心了…其实下午的时候我已经想到是我把 cookie 变量错误地输入为 cookies…但是因为下午没空所以还没改，并且也没来得及回复…

等晚些时候我重新试试。
