### ISSUE TITLE
多帐号签到问题

### ISSUE THREAD

**Issue by wangmanv2** [GamerNoTitle/wyycg-autocheckin#5]
报错内容：
```
[网易云游戏自动签到]验证失败！请检查Cookie是否过期！或者附上报错信息到 https://github.com/GamerNoTitle/wyycg-autosignin/issues 发起issue
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    raise GetInfoError
__main__.GetInfoError
Error: Process completed with exit code 1.
```
Cookie：
`Bearer 
xxxxxxxxxxxxxxx#Bearer 
xxxxxxxxxxxxxxx`
 
单帐号无问题，不过这两个帐号都今天签到过了，是不是这个问题爆的错误呢？Cookie是没过期的。

**Comment by GamerNoTitle** [comment]
emmmm 你应该是没更新
你在你自己的仓库加个PR合并一下更新

**Comment by GamerNoTitle** [comment]
GetInfoError是我上周更新的时候定义的Error，今天已经把它删掉了 :smile:

**Comment by wangmanv2** [comment]
好吧，好象是我之前是用以前的版本。现在是签到成功了，但是最后结束还有点问题。

Traceback (most recent call last):
  File "main.py", line 137, in <module>
    raise Error
__main__.Error
2
***
***

    ```
感谢使用来自<a herf='https://bili33.top'>GamerNoTitle</a>的<a herf='https://github.com/GamerNoTitle/wyycg-autocheckin'>网易云游戏自动签到脚本</a>！<br>
    今日签到结果如下：<br>
    成功数量：2/2<br>
    失败数量：0/2<br>
    具体情况如下：<br>
    第1个账号签到成功！第2个账号签到成功！
    
Error: Process completed with exit code 1.
```

**Comment by GamerNoTitle** [comment]
嗯 我刚刚自己的也报错了 然后发现有一行忘记删掉了
你可以重新更新一下 我刚刚删掉了 实在不好意思 😭

**Comment by wangmanv2** [comment]
更新了，报错还是一样的。
```
Run python3 main.py "***" "" "" "***"
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    raise Error
__main__.Error
2
***
***

    感谢使用来自<a herf='https://bili33.top'>GamerNoTitle</a>的<a herf='https://github.com/GamerNoTitle/wyycg-autocheckin'>网易云游戏自动签到脚本</a>！<br>
    今日签到结果如下：<br>
    成功数量：0/2<br>
    失败数量：2/2<br>
    具体情况如下：<br>
    第1个账号签到失败，回显状态码为400，具体错误信息如下：xxxxxxxxxxxxxxxxx=<br> 第2个账号签到失败，回显状态码为400，具体错误信息如下：xxxxxxxxxxxxx=
    
Error: Process completed with exit code 1.
```

**Comment by GamerNoTitle** [comment]
我想的是有Failure就报错，你今天签到了所以你后面发的这个是今天签到了的报错
开始发的那个其实签到成功了，但是我在判断中条件设置错了就报错了
那个回显我一开始用BASE64在线解过没解出来（手动笑哭）所以就先保留看看怎么解
如果是可以解开的话我这周回去再把它处理掉
可以看看明天的签到结果，如果你更新了最新的版本（今天下午推送的那个）没有问题的话就NP了

**Comment by GamerNoTitle** [comment]
（换成手机来回复）
如果有时间的话可以交个PR（手动滑稽）我会Merge的
要不就等我周末回去更新（嘿嘿）

On Sun, 13 Dec 2020 20:28:44 +0800,  wrote:
> 我想的是有Failure就报错，你今天签到了所以你后面发的这个是今天签到了的报错
> 开始发的那个其实签到成功了，但是我在判断中条件设置错了就报错了
> 那个回显我一开始用BASE64在线解过没解出来（手动笑哭）所以就先保留看看怎么解
> 如果是可以解开的话我这周回去再把它处理掉
> 可以看看明天的签到结果，如果你更新了最新的版本（今天下午推送的那个）没有问题的话就NP了
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/5#issuecomment-744000626
-- 
使用Blackberry 9720发送

**Comment by wangmanv2** [comment]
emmmm 还是有些问题，昨天晚上测试的时候发现，有时候返回不是Base64，我没学过这一类的所以没能解决这个问题。

**Comment by GamerNoTitle** [comment]
> emmmm 还是有些问题，昨天晚上测试的时候发现，有时候返回不是Base64，我没学过这一类的所以没能解决这个问题。

没事 我回去再看看吧 毕竟你给我提供了一个思路

**Comment by GamerNoTitle** [comment]
脚本方面是没有问题了是吗

**Comment by wangmanv2** [comment]
目前没什么问题了。以后有问题会再反馈的。

**Comment by wangmanv2** [comment]
今天签到出现的情况，只要第一个帐号签到成功了，第二个没有成功。
![image.png](https://i.loli.net/2020/12/15/vsj9cbQMUiLgZDN.png)

**Comment by GamerNoTitle** [comment]
有报什么错误吗？贴一下结果信息我看看

On Tue, 15 Dec 2020 10:58:52 +0800,  wrote:
> 今天签到出现的情况，只要第一个帐号签到成功了，第二个没有成功。
> ![image.png](https://i.loli.net/2020/12/15/vsj9cbQMUiLgZDN.png)
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/5#issuecomment-745019677
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by GamerNoTitle** [comment]
@wangmanv2 不好意思我刚刚用的黑莓看不到图 看了一下你的图但是讲真我没法判断是啥原因，看起来好像是第一个账号签到的时候把第二个也签了或者是第二个运行了两次，我周末回去再看看吧

**Comment by GamerNoTitle** [comment]
顺带问一下，你这个第二个帐号签到到底成功了没有？它提示了一次未成功和一次成功，搞得我都不知道到底成功了没有(手动懵逼)

On Tue, 15 Dec 2020 10:58:52 +0800,  wrote:
> 
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by wangmanv2** [comment]
现在才看到，第一个签到成功了，第二个没有签到成功。如果只用一个帐号的话是可以给第二个帐号签到的。

**Comment by GamerNoTitle** [comment]
那我这周末回去试试双帐号，因为我只有一个帐号，测试的时候是借用的别人的帐号且当天两个帐号都签到过了，就没发现这种情况
等周六下午我回家吧 *v*

On Tue, 15 Dec 2020 21:01:06 +0800,  wrote:
> 现在才看到，第一个签到成功了，第二个没有签到成功。如果只用一个帐号的话是可以给第二个帐号签到的。
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/5#issuecomment-745272438
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by GamerNoTitle** [comment]
你合并一下我刚刚推送的"multiusers-debug"分支，然后明天让他自己运行，我看看是哪里触发了错误 3Q

**Comment by GamerNoTitle** [comment]
[wangmanv2/wyycg-autosignin#14](https://github.com/wangmanv2/wyycg-autosignin/pull/14)

**Comment by wangmanv2** [comment]
```
Run python3 main.py "***" "" "" "***"
2
***
No.1: Signerror False but failed
***
No.2: sign except block 1

    感谢使用来自<a herf='https://bili33.top'>GamerNoTitle</a>的<a herf='https://github.com/GamerNoTitle/wyycg-autocheckin'>网易云游戏自动签到脚本</a>！<br>
    今日签到结果如下：<br>
    成功数量：0/2<br>
    失败数量：2/2<br>
    具体情况如下：<br>
    第1个账号签到失败，回显状态码为400，具体错误信息如下：MtkbGCsY2fEyNOPZHCkpGiYbHNnx6O3n6OPZHCkpJCoe2fHZLCocKdcqIB4l1ysmGxgw2ePZHCkpJCoeGiXZ8dkTLOwd7OoTLOzw6fATLOwbHekTLO4Z7hwTLOzp6ufZNME=<br> 第2个账号签到失败，回显状态码为400，具体错误信息如下：MtkbGCsY2fEyNOPZHCkpGiYbHNnx6O3n6OPZHCkpJCoe2fHZLCocKdcqIB4l1ysmGxgw2ePZHCkpJCoeGiXZ8dkTLOwd7OoTLOzw6fATLOwbHekTLO4Z7hwTLOzp6ufZNME=
    
Traceback (most recent call last):
  File "main.py", line 140, in <module>
    raise Error
__main__.Error
Error: Process completed with exit code 1.
```
才看到，第一个账号已经自动签到过了，第二个没有自动签到成功。上面这个是自动签到后手动运行的结果吗，第二个账号仍然没有签到上。但是神奇的是两个账号回显的内容竟然是一样的，

**Comment by GamerNoTitle** [comment]
我是想看看是触发了哪个错误块所以让你merge的，第一个自动签到过了所以这样提示是对的，第二个你今天签到了吗，看样子是requests包进行post的时候就出问题了，再观察两天吧，反正我也得周六回家才能弄

On Thu, 17 Dec 2020 11:31:51 +0800,  wrote:
> 
> ```
> Run python3 main.py "***" "" "" "***"
> 2
> ***
> No.1: Signerror False but failed
> ***
> No.2: sign except block 1
> 
>     感谢使用来自<a herf='https://bili33.top'>GamerNoTitle</a>的<a herf='https://github.com/GamerNoTitle/wyycg-autocheckin'>网易云游戏自动签到脚本</a>！<br>
>     今日签到结果如下：<br>
>     成功数量：0/2<br>
>     失败数量：2/2<br>
>     具体情况如下：<br>
>     第1个账号签到失败，回显状态码为400，具体错误信息如下：MtkbGCsY2fEyNOPZHCkpGiYbHNnx6O3n6OPZHCkpJCoe2fHZLCocKdcqIB4l1ysmGxgw2ePZHCkpJCoeGiXZ8dkTLOwd7OoTLOzw6fATLOwbHekTLO4Z7hwTLOzp6ufZNME=<br> 第2个账号签到失败，回显状态码为400，具体错误信息如下：MtkbGCsY2fEyNOPZHCkpGiYbHNnx6O3n6OPZHCkpJCoe2fHZLCocKdcqIB4l1ysmGxgw2ePZHCkpJCoeGiXZ8dkTLOwd7OoTLOzw6fATLOwbHekTLO4Z7hwTLOzp6ufZNME=
>     
> Traceback (most recent call last):
>   File "main.py", line 140, in <module>
>     raise Error
> __main__.Error
> Error: Process completed with exit code 1.
> ```
> 才看到，第一个账号已经自动签到过了，第二个没有自动签到成功。上面这个是自动签到后手动运行的结果吗，第二个账号仍然没有签到上。但是神奇的是两个账号回显的内容竟然是一样的，
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/5#issuecomment-747182033
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by GamerNoTitle** [comment]
两个返回一样应该是两个都签到过了的原因（我猜），因为你第一个签到过了

On Thu, 17 Dec 2020 11:31:51 +0800,  wrote:
> 
> ```
> Run python3 main.py "***" "" "" "***"
> 2
> ***
> No.1: Signerror False but failed
> ***
> No.2: sign except block 1
> 
>     感谢使用来自<a herf='https://bili33.top'>GamerNoTitle</a>的<a herf='https://github.com/GamerNoTitle/wyycg-autocheckin'>网易云游戏自动签到脚本</a>！<br>
>     今日签到结果如下：<br>
>     成功数量：0/2<br>
>     失败数量：2/2<br>
>     具体情况如下：<br>
>     第1个账号签到失败，回显状态码为400，具体错误信息如下：MtkbGCsY2fEyNOPZHCkpGiYbHNnx6O3n6OPZHCkpJCoe2fHZLCocKdcqIB4l1ysmGxgw2ePZHCkpJCoeGiXZ8dkTLOwd7OoTLOzw6fATLOwbHekTLO4Z7hwTLOzp6ufZNME=<br> 第2个账号签到失败，回显状态码为400，具体错误信息如下：MtkbGCsY2fEyNOPZHCkpGiYbHNnx6O3n6OPZHCkpJCoe2fHZLCocKdcqIB4l1ysmGxgw2ePZHCkpJCoeGiXZ8dkTLOwd7OoTLOzw6fATLOwbHekTLO4Z7hwTLOzp6ufZNME=
>     
> Traceback (most recent call last):
>   File "main.py", line 140, in <module>
>     raise Error
> __main__.Error
> Error: Process completed with exit code 1.
> ```
> 才看到，第一个账号已经自动签到过了，第二个没有自动签到成功。上面这个是自动签到后手动运行的结果吗，第二个账号仍然没有签到上。但是神奇的是两个账号回显的内容竟然是一样的，
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/5#issuecomment-747182033
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by wangmanv2** [comment]
但是第二个没有签到成功，手动运行也没有成功后，刚才我才去手动签到的。

**Comment by wangmanv2** [comment]
emmmmmmmm 我好像搞懂了，你函数名复用了 sign 应该是存储签到地址的，你之后在下面又用来存储 requests 的返回了，怪不得第二个返回的内容一下失败一下成功，而且还返回一样的值。

**Comment by GamerNoTitle** [comment]
怪不得。。。那你修改一下然后交PR？我这边合并一下？（自己都没发现系列）


On Thu, 17 Dec 2020 16:04:53 +0800,  wrote:
> emmmmmmmm 我好像搞懂了，你函数名复用了 sign 应该是存储签到地址的，你之后在下面又用来存储 requests 的返回了，怪不得第二个返回的内容一下失败一下成功，而且还返回一样的值。
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/wyycg-autocheckin/issues/5#issuecomment-747280128
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail
