### ISSUE TITLE
发现个问题

### ISSUE THREAD

**Issue by jc-lw** [GamerNoTitle/wyycg-autocheckin#5]
![image](https://github.com/user-attachments/assets/70be462a-4723-4a34-b296-f62167dc663d)
这怎么解决 佬

**Comment by GamerNoTitle** [comment]
=-=这个不是给你用的 这个是我用来同步的
不推荐用Action，实在要用去把[AutoSignin.yml.disabled](https://github.com/GamerNoTitle/wyycg-autocheckin/blob/master/.github/workflows/AutoSignin.yml.disabled)后面的`.disabled`去掉
